require "inquiry/version"
require "active_record"
require "will_paginate"
require "will_paginate/active_record"
require "inquiry/interpolation_strategies"
require "inquiry/search_clause"
require "inquiry/sort_clause"
require "inquiry/formatters/simple"
require "inquiry/formatters/link_to"
require "inquiry/formatters/currency"
require "inquiry/formatters/datetime"
require "inquiry/formatters/date"
require "inquiry/formatters/phone"
require "inquiry/rollups/base"
require "inquiry/rollups/count"
require "inquiry/rollups/counts"
require "inquiry/rollups/sum"
require "inquiry/rollups/count_percentage"
require "inquiry/rollups/custom"
require "inquiry/search"
require "inquiry/report"

module Inquiry
end
